config/routes.rb
Rails.application.routes.draw do
  resources :items

  resources :categories

	resources :expenses

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
	
	def add_item!(item)
		self.expenses += item.cost
		self.surplus -= item.cost
		self.save
	end
	
	def remove_item!(item)
		self.expenses -= item.cost
		self.surplus += item.cost
		self.save
	end
	
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)
    @category.expenses = 0
    @category.surplus = @category.budget
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :budget, :expenses, :surplus)
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @categories = Category.all
    @amount = @categories.map{|c| c.surplus}.sum
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
      	@item.category.add_item!(@item)
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.category.remove_item!(@item)
    respond_to do |format|
      if @item.update(item_params)
      	@item.category.add_item!(@item)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
  	@item.category.remove_item!(@item)
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :cost, :memo, :category_id, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :budget %><br>
    <%= f.text_field :budget %>
  </div>

  <% if @category.id %>
	  <div class="field">
    	<%= f.label :expenses %><br>
    	<%= f.text_field :expenses %>
  	</div>
	  <div class="field">
	    <%= f.label :surplus %><br>
	    <%= f.text_field :surplus %>
	  </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>
<%= render 'common/nav' %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Budget</th>
      <th>Expenses</th>
      <th>Surplus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.budget %></td>
        <td><%= category.expenses %></td>
        <td><%= category.surplus %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Budget:</strong>
  <%= @category.budget %>
</p>

<p>
  <strong>Expenses:</strong>
  <%= @category.expenses %>
</p>

<p>
  <strong>Surplus:</strong>
  <%= @category.surplus %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/common/_header.html.erb
<% unless current_page?(items_path)||current_page?(categories_path) %>
	<%= link_to 'Listing', items_path %>
<% else %>
	<strong>Listing</strong>
<% end %>

<% unless current_page?(expenses_path) %>
	<%= link_to 'Expenses', expenses_path %>
<% else %>
	<strong>Expenses</strong>
<% end %>

<br><br>

app/views/common/_nav.html.erb
<% unless current_page?(items_path) %>
	<%= link_to 'Listing items', items_path %>
<% else %>
	<strong>Listing items</strong>
<% end %>

<% unless current_page?(categories_path) %>
	<%= link_to 'Listing categories', categories_path %>
<% else %>
	<strong>Listing categories</strong>
<% end %>

<br><br>

app/views/expenses/index.html.erb
<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Budget</th>
      <th>Expenses</th>
      <th>Surplus</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.budget %></td>
        <td><%= category.expenses %></td>
        <td><%= category.surplus %></td>
        <td></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td><%= @amount %></td>
			<td><=Total</td>
      <td></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Index of item', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>
<%= render 'common/nav' %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Cost</th>
      <th>Memo</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.date %></td>
        <td><%= item.name %></td>
        <td><%= item.cost %></td>
        <td><%= item.memo %></td>
        <td><%= item.category.name %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @item.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @item.cost %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @item.memo %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category.name %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Index of item', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExpenseBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'common/header' %>
<%= yield %>

</body>
</html>